### ISSUE TITLE
Old twitter search api

### ISSUE THREAD

**Issue by hzlmn** [h5bp/movethewebforward#104]
Seems like avatars.php file use old twitter rest api (v1 and now v1.1). As this file generete avatar links , page sections  #learn, #ask4help, #helpothers, #feedback, #explore" and other don't work correctly (contributors avatars don't visible).

**Comment by arthurvr** [comment]
Yeah, it's indeed broken atm. If anyone is willing to submit a PR? :)

**Comment by drKraken** [comment]
@arthurvr Seems, like twitter now use secure requests with OAuth, so it's can be tricky for PR, because without application registration request will return "Bad authentication code".
See: https://dev.twitter.com/oauth

**Comment by joel-powers** [comment]
Does this *have* to be done in php? Or could it be done another way? Half if the problem is that this looks to rely on `user_name` when it should be `user_id` instead. But really the caching is booked all over the place and should either be dropped altogether or rewritten. Thoughts?

**Comment by arthurvr** [comment]
> Does this have to be done in php? Or could it be done another way?

I'm personally happy with any way possible. Though I don't know if our server is capable of running much other things than PHP. Would need to double-check that.

> But really the caching is booked all over the place and should either be dropped altogether or rewritten. 

:+1:

**Comment by joel-powers** [comment]
I'm off the opinion that we could skip the cache and just pull in the
avatars with jQuerry... But that's just me.

**Comment by joel-powers** [comment]
After looking at this more closely, with no experience with Twitter's API, I'm now realizing the way this was done originally was - and still is - the best way.

The problem is that the API requires an oAuth token now, which was not required in v1, when this repo was created. I don't mind having on this, but the PHP file will have to be .gitignore'd for security and authored by someone else. Preferably, this should be the owner of the MTWF Twitter account.

At that point, there isn't much else to do. The .js file isn't going to change much. Or am I missing something?
